name: "New PR Process Tester"

on:
  pull_request:
    types:
      - opened
      - synchronize 
    branches:
      - main
      # - 'feature/development'


jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs: 
      branch: ${{ steps.extract_branch.outputs.branch }}
      changes: ${{ steps.extract_changes.outputs.changes }}
    steps:
      - name: Show run details
        run: |
          echo 'GitHub Run Details'
          echo 'github.run_id = ${{ github.run_id }}'
          echo 'github.run_number = ${{ github.run_number }}'
          echo 'github.run_attempt = ${{ github.run_attempt }}'
          
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Check Variables
        run: |
          echo 'github.base_ref = ${{ github.base_ref }}'
          echo 'github.event.head_commit.message = ${{ github.event.head_commit.message }}'
          echo 'steps.extract_branch.outputs.branch = ${{ steps.extract_branch.outputs.branch }}'
          echo 'github.event.action = ${{ github.event.action }}'
          echo 'github.event.pusher.name = ${{ github.event.pusher.name }}'
          echo 'github.event.repository.full_name = ${{  github.event.repository.full_name }}'
          echo 'github.event.pull_request.html_url = ${{  github.event.pull_request.html_url }}'
          echo 'github.event.pull_request.head.html_url = ${{  github.event.pull_request.head.html_url }}'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Verify files updated in pull request
        id: extract_changes    
        run: |
          list_of_changes=$(git diff --name-only -r HEAD^1 HEAD | tr ' ' '/')
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "$list_of_changes"
          echo "changes<<$EOF" >> $GITHUB_OUTPUT
          echo "$list_of_changes" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
        
  tester:
    if: contains(needs.check-branch.outputs.branch, 'REAL') || contains(needs.check-branch.outputs.branch, 'RR') && github.event.action == 'opened'
    name: Test the action
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    needs: check-branch
    steps:
      - name: Assign QA to PR
        uses: kentaro-m/auto-assign-action@v1.2.5

      - name: Login to JIRA
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }} 
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }} 
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }} 
  
      - name: Find Issue Key
        uses: atlassian/gajira-find-issue-key@v3
        id: ticket
        with:
          string: ${{ needs.check-branch.outputs.branch }}
  
      - name: Comment PR on JIRA ticket
        uses: atlassian/gajira-comment@v3
        with:
          issue: ${{ steps.ticket.outputs.issue }}
          comment: 'Pull Request: ${{ github.event.pull_request.html_url }}'
  
      - name: Comment file changes on JIRA ticket
        uses: atlassian/gajira-comment@v3
        with:
          issue: ${{ steps.ticket.outputs.issue }}
          comment: |
            File Changes:  
            ${{ needs.check-branch.outputs.changes }}
  
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }}) pull request opened for [${{ steps.ticket.outputs.issue }}.](https://designworksgaming.atlassian.net/browse/${{ steps.ticket.outputs.issue }}) 
            <br>
            [Demo URL](https://dwg-dev.rmg.designworksgames.com/${{ needs.check-branch.outputs.branch }}/portal/index.html)

      - name: Check Variables
        run: |
          echo 'steps.ticket.outputs.issue = ${{ steps.ticket.outputs.issue }}'
          echo 'needs.extract_branch.outputs.branch = ${{ needs.check-branch.outputs.branch }}'