name: "New PR Process Tester"

on:
  pull_request:
    types:
      - opened
      - synchronize 
    branches:
      - main
      # - 'feature/development'


jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs: 
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Show run details
        run: |
          echo 'GitHub Run Details'
          echo 'github.run_id = ${{ github.run_id }}'
          echo 'github.run_number = ${{ github.run_number }}'
          echo 'github.run_attempt = ${{ github.run_attempt }}'

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Check Variables
        run: |
          echo 'github.base_ref = ${{ github.base_ref }}'
          echo 'github.event.head_commit.message = ${{ github.event.head_commit.message }}'
          echo 'steps.extract_branch.outputs.branch = ${{ steps.extract_branch.outputs.branch }}'
          echo 'github.event.action = ${{ github.event.action }}'

  tester:
    if: contains(needs.check-branch.outputs.branch, 'REAL')
    name: Test the action
    runs-on: ubuntu-latest
    needs: check-branch
    steps:
    - name: Assign QA to PR
      uses: kentaro-m/auto-assign-action@v1.2.5
      with:
        repo-token: ${{ secrets.PAT_TOKEN }}

    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }} 
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }} 
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }} 

    - name: Check Variables
      run: |
        echo 'steps.ticket.outputs.issue = ${{ steps.ticket.outputs.issue }}'
        echo 'needs.extract_branch.outputs.branch = ${{ needs.check-branch.outputs.branch }}'